### PR TITLE
Ref task #3034_create_UI_public_room

### PR DESCRIPTION
**Pull request by manhphan34**
Refs task 3034 create UI public room

### Summary:
- [Feature] Init Home Screen
### Link Issue:
- https://edu-redmine.framgia.vn/issues/3034

### CODE REVIEW

**Comment by manhphan34** [comment]
ready

**Review by DoanVanToan — COMMENTED** [review]
tên icon có tiền tố 
ic_abc_xyz

**Comment by DoanVanToan** [comment]
commented

**Comment by manhphan34** [comment]
ready

**Review by DoanVanToan — APPROVED** [review]
LGTM

**Pull request merged**
